version: "3.8"

services:
  frontend:
    build:
      context: .
      args:
        NEXT_PUBLIC_API_URL: "http://host.docker.internal:3000"
    container_name: task-manager-front
    ports:
      - "4000:3000" 
    restart: unless-stopped
